In [1]:
import tensorflow as tf

In [2]:
# make computational graph for SVD (singular value decomposition)
# ref: https://www.tensorflow.org/api_docs/python/tf/svd

A = tf.placeholder(tf.float32)
s, U, V = tf.svd(A) # A = U*diag(s)*V^T

diag_s = tf.diag(s)
V_T = tf.transpose(V)
reconst_A = tf.matmul(tf.matmul(U,diag_s), V_T)

In [3]:
sess = tf.Session()

In [4]:
input_matrix = [[1, 2, 3],
                [9, 8, 7]]
singular, mat_U, mat_V = sess.run([s, U, V], {A:input_matrix})

In [5]:
print '- output shape check'
print (singular.shape, mat_U.shape, mat_V.shape)
print
print '- singular value'
print singular
print
print '- right singular vectors'
print mat_U
print
print '- left singular vectors'
print mat_V

- output shape check
((2,), (2, 2), (3, 2))

- singular value
[ 14.32041454   1.71048856]

- right singular vectors
[[-0.23405695 -0.97222292]
 [-0.97222292  0.23405695]]

- left singular vectors
[[-0.62736064  0.66313809]
 [-0.57581419 -0.04208755]
 [-0.52426785 -0.74731302]]


In [6]:
print '- reconstruction matrix A'
print(sess.run(reconst_A, {A:input_matrix}))

- reconstruction matrix A
[[ 0.99999988  2.00000024  3.00000095]
 [ 9.00000191  8.00000095  7.00000191]]


In [7]:
input_matrix1 = [[1, 2, 3],
                [9, 8, 7]]
input_matrix2 = [[100, 0.1, 2],
                [7, 128, 64]]
input_tensor = [input_matrix1, input_matrix2, input_matrix1, input_matrix2]
singular, mat_U, mat_V = sess.run([s, U, V], {A:input_tensor})
print (singular.shape, mat_U.shape, mat_V.shape)

((4, 2), (4, 2, 2), (4, 3, 2))


In [8]:
print '- singular value'
print singular[0]
print
print '- right singular vectors'
print mat_U[0]
print
print '- left singular vectors'
print mat_V[0]

- singular value
[ 14.32041454   1.71048856]

- right singular vectors
[[-0.23405695 -0.97222292]
 [-0.97222292  0.23405695]]

- left singular vectors
[[-0.62736064  0.66313809]
 [-0.57581419 -0.04208755]
 [-0.52426785 -0.74731302]]
